version: "3.3"
services:
  mysqlLocal:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./mysqlData/:/var/lib/mysql"
  redisLocal:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - "./redisData/:/var/lib/mysql"
